package com.ashokit.constant;

public enum MessageConstant {
	LOCK, UNLOCK, 
	EMAIL_ID_ALL_READY_REGISTER, 
	YOU_HAVE_REGISTER_SUCCESSFULLY_PLEASE_CHECK_EMAIL_FOR_ACTIVATION,
	YOUR_ACCOUNT_ACTIVATED_SUCCESSFULLY,
	PLEASE_CHECK_TEMPORARY_YOU_HAVE_GIVEN_WRONG_PASSWORD,
	YOU_HAVE_SUCCESSFULLY_LOGIN,
	YOU_HAVE_NOT_ACTIVATED_YOUR_ACCOUNT_PLEASE_ACTIVATE,
	BEFORE_LOGING_PLEASE_ACTIVATE_YOUR_ACCOUNT,
	YOU_HAVE_SUCCEFULLY_LOGING,
	TEMP_PASSWORD_HAS_SENT_PLEASE_CHECK_MAIL_FOR_RESET_PASSWORD, YOUR_ACCOUNT_PASSWORD_RESET_SUCCESSFULLY;
	
	
	
	
	
	
	

}
